version: "3.9"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
    expose:
      - "8000"
    restart: always

  telegram_bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - web
    environment:
      # Use the FastAPI service’s hostname in Docker (not localhost)
      API_LOGIN_URL: "http://web:8000/auth/login"
      API_CHECK_EMAIL_URL: "http://web:8000/auth/check_email"
      # Replace with your actual bot token or set it as an environment variable
      BOT_TOKEN: "8103489251:AAEw30I0rifou8Ehx_Du2R_TCLEzA6w_Sbk"
    command: python telegram_bot.py
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
